version: '1.0.{build}'

platform:
  - x86
configuration:
  - Release

environment:
  matrix:
    - PYTHON: "C:\\Python35"

services:
  - mongodb

before_build:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe deploy_scripts/set_app_version_during_ci.py v%APPVEYOR_BUILD_VERSION%"

build_script:
  - "%PYTHON%\\python.exe cx_setup.py build"

#after_build:
#  - "7z a kaira-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\\build\\exe.win32-3.5"

before_test:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
          $wc.DownloadFile("https://github.com/Learning-from-our-past/Kaira/releases/download/v1.0/mongodump.zip", "$($env:APPVEYOR_BUILD_FOLDER)\mongodump.zip")
- "7z x %APPVEYOR_BUILD_FOLDER%\\mongodump.zip"
- cmd: dir
- cmd: C:\mongodb\bin\mongorestore.exe %APPVEYOR_BUILD_FOLDER%\\dump\

test: off

test_script:
- "%PYTHON%\\python.exe -m pytest --junitxml=test-results.xml"
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results.xml))


#artifacts:
#  - path: "kaira-%APPVEYOR_BUILD_VERSION%.zip"
#    name: Kaira

skip_tags: true

#deploy:
#  - provider: GitHub
#    release: v$(appveyor_build_version)
#    artifact: /.*\.zip/           # upload all zip files
#    draft: false
#    prerelease: false
#    on:
#      branch: master # deploy on push to master
#    description: "Appveyor automatic build. Please install by copying contents of the zip file into base install folder.\n\n$(APPVEYOR_REPO_COMMIT_MESSAGE)"
#    auth_token:
#      secure: dVhUugZ838SU7EjJOeQRNhX/PFvsx9cnsERrZhzLZXkwnmNbP/iKywebkrrFTAzd

