KEYS = {
      "name" : "name",
      "farmLocation" : "FarmLocation",
      "ownerFrom" : "OwnerFrom",
      "ownerName" : "OwnerName",
      "surname" : "Surname",
      "firstnames" : "FirstNames",
      "owner": "Owner",
      "ownerBirthData" : "birthData",
      "hostessBirthData" : "birthData",
      "hostess": "Hostess",

      "farmDetails" : "farmDetails",
      "wholeArea" : "wholeArea",
      "forestArea" : "forestArea",
      "fieldArea" : "fieldArea",
      "wasteArea" : "wasteArea",
      "meadowArea" : "meadowArea",

      "flags" : "flags",
      "oat" : "Oat",
      "barley" : "Barley",
      "rye" : "Rye",
      "hay" : "Hay",
      "potatoes" : "Potatoes",
      "lanttu" : "Lanttu",
      "wheat" : "Wheat",
      "sugarbeet" : "Sugarbeet",
      "puimakone" : "ThreshingMachine",
      "tractor" : "Tractor",
      "horse" : "Horse",
      "chicken" : "Chicken",
      "siirtotila" : "Siirtotila",
      "kantatila" : "Kantatila",
      "salaojitus" : "Salaojitus",
      "lypsykone" : "Lypsykone",
      "sauna" : "Sauna",
      "navetta" : "Navetta",
      "autotalli" : "Autotalli",
      "talli" : "Talli",
      "birch" : "Birch",
      "spruce" : "Spruce",
      "pine" : "Pine",
      "someonedead" : "SomeoneDead",

      "moreeni" : "Moreeni",
      "hieta" : "Hieta",
      "hiesu" : "Hiesu",
      "muta" : "Muta",
      "savi" : "Savi",
      "multa" : "Multa",

      "rooms" : "rooms",
      "lypsylehma" : "lypsylehma",
      "teuras" : "teuraselain",
      "lammas" : "lammas",
      "lihotussika" : "lihotussika",
      "emakko" : "emakko",
      "nuori" : "nuori",
      "kanoja" : "kanoja",

      "quantities" : "quantities",




      "origfamily" : "OriginalFamily",
      "profession" : "Profession/Status",
      "imagepath": "ImagePath",
      "approximatePage" : "ApproximatePageNumber",
      "omakotitalo" : "Omakotitalo",
      "karelianlocations" : "KarelianLocations",
      "karelianlocation" : "KarelianLocation",
      "returnedkarelia": "ReturnedToKarelia",
      "kareliancoordinate": "KarelianCoordinates",
      "karelianlocationsCount": "KarelianLocationCount",
      "otherlocations" : "OtherLocations",
      "otherlocationsCount" : "OtherLocationCount",
      "otherlocation" : "OtherLocation",
      "othercoordinate": "OtherCoordinates",
      "manymarriages" : "MaybePreviousMarriages",
      "spouseDeathYear": "spouseDeathYear",


      "birthDay" :  "BirthDay",
      "birthMonth" : "BirthMonth",
      "birthYear" : "BirthYear",
      "birthLocation" : "BirthLocation",

      "address" : "Address",
      "deathDay" : "DeathDay",
      "deathMonth" : "DeathMonth",
      "deathYear" : "DeathYear",
      "kaatunut" : "Fallen",
      "deathLocation" : "DeathLocation",
      "talvisota" : "Talvisota",
      "talvisotaregiments" : "TalvisotaRegiments",
      "jatkosota" : "Jatkosota",
      "jatkosotaregiments" : "JatkosotaRegiments",
      "rank": "Rank",
      "kotiutusDay" : "DemobilizationDay",
      "kotiutusMonth" : "DemobilizationMonth",
      "kotiutusYear" : "DemobilizationYear",
      "kotiutusPlace" : "DemobilizationLocation",
      "medals" : "Medals",
      "hobbies" : "Hobbies",
      "hasSpouse" : "HasSpouse",
      "weddingYear" : "WeddingYear",

      "spouse": "Spouse",
      "spouseName" : "SpouseName",
      "spouseProfession" : "SpouseProfession",
      "spouseBirthData" : "SpouseBirthData",
      "spouseDeathData" : "SpouseDeathData",
      "spouseOrigFamily" : "SpouseOriginalFamily",
      "children" : "Children",
      "gender" : "Gender",
      "girlCount" : "girlCount",
      "boyCount" : "boyCount",


      "separated" : "Separated",
      "miehEd" : "ManPreviousMarriage",
      "nyk" : "ManCurrentMarriage",
      "psoEd" : "SpousePreviousMarriage",
      "wifeList" : "Wives",
      "spouseCount" : "SpouseCount",
      "cursorLocation" : "cursorLocation",
      "childCount" : "ChildCount",
      "spouseBirthLocation" : "SpouseBirthLocation",
      "regiments" : "Regiments"


}


