# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 694)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.entriesFrame = QtWidgets.QFrame(self.centralwidget)
        self.entriesFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.entriesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.entriesFrame.setObjectName("entriesFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.entriesFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.entriesControlLayout = QtWidgets.QFormLayout()
        self.entriesControlLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.entriesControlLayout.setObjectName("entriesControlLayout")
        self.entriesLabel = QtWidgets.QLabel(self.entriesFrame)
        self.entriesLabel.setObjectName("entriesLabel")
        self.entriesControlLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.entriesLabel)
        self.entriesComboBox = QtWidgets.QComboBox(self.entriesFrame)
        self.entriesComboBox.setMaxVisibleItems(20)
        self.entriesComboBox.setObjectName("entriesComboBox")
        self.entriesComboBox.addItem("")
        self.entriesControlLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.entriesComboBox)
        self.verticalLayout_4.addLayout(self.entriesControlLayout)
        self.entriestListView = EntriesListView(self.entriesFrame)
        self.entriestListView.setStyleSheet("QListWidget {\n"
"alternate-background-color: #EDEDED;\n"
"background-color: white;\n"
"}")
        self.entriestListView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entriestListView.setAlternatingRowColors(True)
        self.entriestListView.setObjectName("entriestListView")
        self.verticalLayout_4.addWidget(self.entriestListView)
        self.horizontalLayout_2.addWidget(self.entriesFrame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.previousFrame = QtWidgets.QFrame(self.centralwidget)
        self.previousFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.previousFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.previousFrame.setObjectName("previousFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.previousFrame)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.previousControlsLayout = QtWidgets.QHBoxLayout()
        self.previousControlsLayout.setSpacing(2)
        self.previousControlsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.previousControlsLayout.setContentsMargins(-1, -1, -1, 0)
        self.previousControlsLayout.setObjectName("previousControlsLayout")
        self.previousEntryLabel = QtWidgets.QLabel(self.previousFrame)
        self.previousEntryLabel.setObjectName("previousEntryLabel")
        self.previousControlsLayout.addWidget(self.previousEntryLabel)
        self.verticalLayout_3.addLayout(self.previousControlsLayout)
        self.previousEntryTextEdit = QtWidgets.QPlainTextEdit(self.previousFrame)
        self.previousEntryTextEdit.setObjectName("previousEntryTextEdit")
        self.verticalLayout_3.addWidget(self.previousEntryTextEdit)
        self.rawTextLabel = QtWidgets.QLabel(self.previousFrame)
        self.rawTextLabel.setObjectName("rawTextLabel")
        self.verticalLayout_3.addWidget(self.rawTextLabel)
        self.rawTextTextEdit = QtWidgets.QPlainTextEdit(self.previousFrame)
        self.rawTextTextEdit.setObjectName("rawTextTextEdit")
        self.verticalLayout_3.addWidget(self.rawTextTextEdit)
        self.label = QtWidgets.QLabel(self.previousFrame)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.nextEntryTextEdit = QtWidgets.QPlainTextEdit(self.previousFrame)
        self.nextEntryTextEdit.setObjectName("nextEntryTextEdit")
        self.verticalLayout_3.addWidget(self.nextEntryTextEdit)
        self.gridLayout.addWidget(self.previousFrame, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.treeView = EntryTreeView(self.centralwidget)
        self.treeView.setMinimumSize(QtCore.QSize(631, 0))
        self.treeView.setMaximumSize(QtCore.QSize(631, 16777215))
        self.treeView.setUniformRowHeights(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAnimated(True)
        self.treeView.setWordWrap(True)
        self.treeView.setExpandsOnDoubleClick(False)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(True)
        self.treeView.header().setDefaultSectionSize(100)
        self.treeView.header().setHighlightSections(True)
        self.treeView.header().setMinimumSectionSize(399)
        self.treeView.header().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.treeView)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_XML_for_analyze = QtWidgets.QAction(MainWindow)
        self.actionOpen_XML_for_analyze.setObjectName("actionOpen_XML_for_analyze")
        self.actionCsv = QtWidgets.QAction(MainWindow)
        self.actionCsv.setObjectName("actionCsv")
        self.actionJSON = QtWidgets.QAction(MainWindow)
        self.actionJSON.setObjectName("actionJSON")
        self.actionOpen_txt = QtWidgets.QAction(MainWindow)
        self.actionOpen_txt.setObjectName("actionOpen_txt")
        self.actionSave_changes_to_xml = QtWidgets.QAction(MainWindow)
        self.actionSave_changes_to_xml.setObjectName("actionSave_changes_to_xml")
        self.actionFrom_txt_OCR = QtWidgets.QAction(MainWindow)
        self.actionFrom_txt_OCR.setObjectName("actionFrom_txt_OCR")
        self.actionRun_analysis_for_all = QtWidgets.QAction(MainWindow)
        self.actionRun_analysis_for_all.setObjectName("actionRun_analysis_for_all")
        self.actionRun_analysis_for_current = QtWidgets.QAction(MainWindow)
        self.actionRun_analysis_for_current.setObjectName("actionRun_analysis_for_current")
        self.actionCreate_a_new_Person = QtWidgets.QAction(MainWindow)
        self.actionCreate_a_new_Person.setObjectName("actionCreate_a_new_Person")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuExport.addAction(self.actionCsv)
        self.menuExport.addAction(self.actionJSON)
        self.menuImport.addAction(self.actionFrom_txt_OCR)
        self.menuFile.addAction(self.actionOpen_XML_for_analyze)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_changes_to_xml)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionCreate_a_new_Person)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kaira"))
        self.entriesLabel.setText(_translate("MainWindow", "Entries "))
        self.entriesComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.previousEntryLabel.setText(_translate("MainWindow", "Previous entry"))
        self.rawTextLabel.setText(_translate("MainWindow", "Current entry"))
        self.label.setText(_translate("MainWindow", "Next entry"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_XML_for_analyze.setText(_translate("MainWindow", "Open xml"))
        self.actionCsv.setText(_translate("MainWindow", "CSV"))
        self.actionJSON.setText(_translate("MainWindow", "JSON"))
        self.actionOpen_txt.setText(_translate("MainWindow", "Open txt"))
        self.actionSave_changes_to_xml.setText(_translate("MainWindow", "Save As..."))
        self.actionFrom_txt_OCR.setText(_translate("MainWindow", "From OCR"))
        self.actionRun_analysis_for_all.setText(_translate("MainWindow", "Run analysis for all"))
        self.actionRun_analysis_for_all.setToolTip(_translate("MainWindow", "Run analysis for all entries in current file"))
        self.actionRun_analysis_for_all.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.actionRun_analysis_for_current.setText(_translate("MainWindow", "Run analysis for current"))
        self.actionRun_analysis_for_current.setToolTip(_translate("MainWindow", "Run extraction for current person and update attributes"))
        self.actionRun_analysis_for_current.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionCreate_a_new_Person.setText(_translate("MainWindow", "Create a  new Person"))
        self.actionCreate_a_new_Person.setToolTip(_translate("MainWindow", "Create a new person from rawtext"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from qtgui.entriesModels import EntriesListView
from qtgui.entrytree import EntryTreeView
