KEYS = {
      "approximatePage" : "approximatePageNumber",
      "name" : "farmName",
      "farmLocation" : "farmLocation",
      "ownerFrom" : "ownerFrom",
      "ownerName" : "ownerName",
      "surname" : "surname",
      "firstnames" : "firstNames",
      "owner": "owner",
      "ownerBirthData" : "birthData",
      "hostessBirthData" : "birthData",
      "hostess": "hostess",

      "farmDetails" : "farmDetails",
      "wholeArea" : "wholeArea",
      "forestArea" : "forestArea",
      "fieldArea" : "fieldArea",
      "wasteArea" : "wasteArea",
      "meadowArea" : "meadowArea",

      "flags" : "keywordFlags",
      "oat" : "oat",
      "barley" : "barley",
      "rye" : "rye",
      "hay" : "hay",
      "potatoes" : "potatoes",
      "lanttu" : "lanttu",
      "wheat" : "wheat",
      "sugarbeet" : "sugarbeet",
      "puimakone" : "threshingMachine",
      "tractor" : "tractor",
      "horse" : "horse",
      "chicken" : "chicken",
      "siirtotila" : "siirtotila",
      "kantatila" : "kantatila",
      "salaojitus" : "salaojitus",
      "lypsykone" : "lypsykone",
      "sauna" : "sauna",
      "navetta" : "navetta",
      "autotalli" : "autotalli",
      "talli" : "talli",
      "birch" : "birch",
      "spruce" : "spruce",
      "pine" : "pine",
      "someonedead" : "someoneDead",

      "moreeni" : "moreeni",
      "hieta" : "hieta",
      "hiesu" : "hiesu",
      "muta" : "muta",
      "savi" : "savi",
      "multa" : "multa",

      "rooms" : "rooms",
      "lypsylehma" : "lypsylehma",
      "teuras" : "teuraselain",
      "lammas" : "lammas",
      "lihotussika" : "lihotussika",
      "emakko" : "emakko",
      "nuori" : "nuori",
      "kanoja" : "kanoja",

      "quantities" : "quantities",




      "origfamily" : "OriginalFamily",
      "profession" : "Profession/Status",
      "imagepath": "ImagePath",
      "approximatePage" : "approximatePageNumber",
      "omakotitalo" : "Omakotitalo",
      "karelianlocations" : "KarelianLocations",
      "karelianlocation" : "KarelianLocation",
      "returnedkarelia": "ReturnedToKarelia",
      "kareliancoordinate": "KarelianCoordinates",
      "karelianlocationsCount": "KarelianLocationCount",
      "otherlocations" : "OtherLocations",
      "otherlocationsCount" : "OtherLocationCount",
      "otherlocation" : "OtherLocation",
      "othercoordinate": "OtherCoordinates",
      "manymarriages" : "maybePreviousMarriages",
      "spouseDeathYear": "spouseDeathYear",


      "birthDay" :  "birthDay",
      "birthMonth" : "birthMonth",
      "birthYear" : "birthYear",
      "birthLocation" : "birthLocation",

      "address" : "Address",
      "deathDay" : "DeathDay",
      "deathMonth" : "DeathMonth",
      "deathYear" : "DeathYear",
      "kaatunut" : "Fallen",
      "deathLocation" : "DeathLocation",
      "talvisota" : "Talvisota",
      "talvisotaregiments" : "TalvisotaRegiments",
      "jatkosota" : "Jatkosota",
      "jatkosotaregiments" : "JatkosotaRegiments",
      "rank": "Rank",
      "kotiutusDay" : "DemobilizationDay",
      "kotiutusMonth" : "DemobilizationMonth",
      "kotiutusYear" : "DemobilizationYear",
      "kotiutusPlace" : "DemobilizationLocation",
      "medals" : "Medals",
      "hobbies" : "Hobbies",
      "hasSpouse" : "HasSpouse",
      "weddingYear" : "WeddingYear",

      "spouse": "Spouse",
      "spouseName" : "SpouseName",
      "spouseProfession" : "SpouseProfession",
      "spouseBirthData" : "SpouseBirthData",
      "spouseDeathData" : "SpouseDeathData",
      "spouseOrigFamily" : "SpouseOriginalFamily",
      "children" : "children",
      "gender" : "gender",
      "girlCount" : "girlCount",
      "boyCount" : "boyCount",


      "separated" : "Separated",
      "miehEd" : "ManPreviousMarriage",
      "nyk" : "ManCurrentMarriage",
      "psoEd" : "SpousePreviousMarriage",
      "wifeList" : "Wives",
      "spouseCount" : "SpouseCount",
      "cursorLocation" : "cursorLocation",
      "childCount" : "childCount",
      "spouseBirthLocation" : "SpouseBirthLocation",
      "regiments" : "Regiments"


}


