KEYS = {
      "surname" : "Surname",
      "firstnames" : "First names",
      "birthDay" :  "BirthDay",
      "birthMonth" : "BirthMonth",
      "birthYear" : "BirthYear",
      "birthLocation" : "BirthLocation",
      "profession" : "Profession",
      "address" : "Address",
      "deathDay" : "DeathDay",
      "deathMonth" : "DeathMonth",
      "deathYear" : "DeathYear",
      "kaatunut" : "Fallen",
      "deathLocation" : "DeathLocation",
      "talvisota" : "Talvisota",
      "talvisotaregiments" : "Talvisota regiments",
      "jatkosota" : "Jatkosota",
      "jatkosotaregiments" : "Jatkosota regiments",
      "rank": "Rank",
      "kotiutusDay" : "DemobilizationDay",
      "kotiutusMonth" : "DemobilizationMonth",
      "kotiutusYear" : "DemobilizationYear",
      "kotiutusPlace" : "DemobilizationLocation",
      "medals" : "Medals",
      "hobbies" : "Hobbies",
      "hasSpouse" : "Has spouse",
      "weddingYear" : "WeddingYear",
      "spouseName" : "Spouse name",
      "spouseBirthData" : "Spouse birth data",
      "spouseDeathData" : "Spouse death data",
      "children" : "Children",
      "separated" : "Separated",
      "miehEd" : "Man's previous marriage",
      "nyk" : "Man's current marriage",
      "psoEd" : "Spouse's previous marriage",
      "wifeList" : "Wives",
      "spouseCount" : "Spouse count",
      "cursorLocation" : "cursorLocation",
      "childCount" : "Child count",
      "spouseBirthLocation" : "Spouse birth location",
      "regiments" : "Regiments"


}