KEYS = {
      "surname" : "Surname",
      "firstnames" : "FirstNames",
      "origfamily" : "OriginalFamily",
      "profession" : "Profession/Status",
      "imagepath": "ImagePath",
      "omakotitalo" : "Omakotitalo",
      "karelianlocations" : "KarelianLocations",
      "karelianlocation" : "KarelianLocation",
      "returnedkarelia": "ReturnedToKarelia",
      "kareliancoordinate": "KarelianCoordinates",
      "otherlocations" : "OtherLocations",
      "otherlocation" : "OtherLocation",
      "othercoordinate": "OtherCoordinates",


      "birthDay" :  "BirthDay",
      "birthMonth" : "BirthMonth",
      "birthYear" : "BirthYear",
      "birthLocation" : "BirthLocation",

      "address" : "Address",
      "deathDay" : "DeathDay",
      "deathMonth" : "DeathMonth",
      "deathYear" : "DeathYear",
      "kaatunut" : "Fallen",
      "deathLocation" : "DeathLocation",
      "talvisota" : "Talvisota",
      "talvisotaregiments" : "TalvisotaRegiments",
      "jatkosota" : "Jatkosota",
      "jatkosotaregiments" : "JatkosotaRegiments",
      "rank": "Rank",
      "kotiutusDay" : "DemobilizationDay",
      "kotiutusMonth" : "DemobilizationMonth",
      "kotiutusYear" : "DemobilizationYear",
      "kotiutusPlace" : "DemobilizationLocation",
      "medals" : "Medals",
      "hobbies" : "Hobbies",
      "hasSpouse" : "HasSpouse",
      "weddingYear" : "WeddingYear",

      "spouse": "Spouse",
      "spouseName" : "SpouseName",
      "spouseProfession" : "SpouseProfession",
      "spouseBirthData" : "SpouseBirthData",
      "spouseDeathData" : "SpouseDeathData",
      "children" : "Children",
      "separated" : "Separated",
      "miehEd" : "ManPreviousMarriage",
      "nyk" : "ManCurrentMarriage",
      "psoEd" : "SpousePreviousMarriage",
      "wifeList" : "Wives",
      "spouseCount" : "SpouseCount",
      "cursorLocation" : "cursorLocation",
      "childCount" : "ChildCount",
      "spouseBirthLocation" : "SpouseBirthLocation",
      "regiments" : "Regiments"


}


