#!/bin/sh

RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 6)
NORMAL=$(tput sgr0)

if ! command -v invoke &> /dev/null
then
  printf "${RED}ERROR: ${CYAN}invoke${RED} not found.\n"
  printf "Is your virtualenv active and have you installed the requirements?\n"
  exit 1
fi

if ! command -v black &> /dev/null
then
  printf "${RED}ERROR: ${CYAN}black${RED} not found.\n"
  printf "Is your virtualenv active and have you installed the requirements?\n"
  exit 1
fi

inv code-check
printf "\n"

if [ $? -ne 0 ]; then
  printf "${YELLOW}The code format check exited with a non-zero status code.\n"
  printf "Consider formatting your files: ${CYAN}inv code-format\n"
  exit 1
fi

printf "${GREEN}Code format checks out. Proceeding to commit.\n"
exit 0

