book_series: "Suomen Pienviljelijät"
pipeline:
  - !Extractor {
      module: "book_extractors.greatfarmers.extractors.metadata_extractor",
      class_name: "MetadataExtractor"
    }

  - !Extractor {
      module: "book_extractors.greatfarmers.extractors.owner_extractor",
      class_name: "OwnerExtractor",
      pipeline: [
       !Extractor {
          module: "book_extractors.greatfarmers.extractors.birthday_extractor",
          class_name: "BirthdayExtractor"
        }
      ]
    }

  - !Extractor {
      module: "book_extractors.greatfarmers.extractors.spouse_extractor",
      class_name: "SpouseExtractor",
      pipeline: [
       !Extractor {
          module: "book_extractors.greatfarmers.extractors.birthday_extractor",
          class_name: "BirthdayExtractor"
        },
        !Extractor {
          module: "book_extractors.greatfarmers.extractors.original_family_extractor",
          class_name: "FormerSurnameExtractor"
        }
      ]
    }

  - !Extractor {
      module: "book_extractors.greatfarmers.extractors.farm_extractor",
      class_name: "FarmExtractor"
    }

  - !Extractor &Birthday {
      module: "book_extractors.greatfarmers.extractors.child_extractor",
      class_name: "ChildExtractor"
    }

  - !Extractor {
      module: "book_extractors.common.extractors.previous_marriages_flag_extractor",
      class_name: "PreviousMarriagesFlagExtractor"
    }

  - !Extractor {
      module: "book_extractors.common.extractors.bool_extractor",
      class_name: "BoolExtractor",
      options: {
        patterns: {
          garage: 'autotalli',
          barley: 'ohra',
          birch: 'koivu(?!nen|niem)',
          chicken: 'kanoja|\skanaa',
          cowhouse: 'navetta|navetan',
          hay: '(heinä(?!mäki))',
          hiesu: 'hiesu',
          hieta: '(hieta(?!nen))',
          horse: 'hevonen|hevos',
          kantatila: 'kantatila',
          moreeni: 'moreeni',
          mud: 'muta',
          oat: '(kaura(?!nen))',
          pine: 'mänty(?!nen)',
          potatoes: 'peruna',
          rye: 'ruis',
          salaojitus: '(salaojitettu|salaojitus)',
          sauna: 'sauna',
          savi: '(savi(?!taipale))',
          siirtotila: 'siirtotila',
          soil: 'multa',
          someoneDead: 'kuoli|kuollut|kaatui|kaatunut',
          spruce: 'kuusi(?!nen)',
          stable: '(?!auto)talli',
          sugarbeet: 'sokerijuuri',
          swedishTurnip: 'lanttu',
          threshingMachine: 'puimakone',
          tractor: 'traktori',
          wheat: 'vehnä',
          viljankuivuri: 'viljankuivuri',
          kotitalousmylly: 'kotitalousmylly',
          aykarja: 'ay-karja',
          skkarja: 'sk-karja'
        }
      }
    }

  - !Extractor {
      module: "book_extractors.greatfarmers.extractors.quantity_extractor",
      class_name: "QuantityExtractor",
      options: {
        patterns: {
          emakko: '(?:(?:(?:emakkoja on\s?){s<=1,i<=1})|(?:\semakkoa))',
          chicken: '(?:(?:(?:kanoja (?:on\s?)?){s<=1,i<=1})|(?:\skanaa))',
          sheep: '(?:(?:(?:lampaita (?:on\s?)?){s<=1,i<=1})|(?:\slammasta))',
          lihotussika: '(?:lihotus-?sik){s<=1,i<=1}',
          dairyCow: '(?:(?:lypsävää){s<=1,i<=1}|(?:lypsylehmää){s<=1,i<=1})',
          nuori: '(?:(?:nuorta){s<=1,i<=1})',
          rooms: '(?:(?:asuinhuonetta){s<=1,i<=1}|(?:huonetta){s<=1,i<=1})'
        }
      }
    }

  - !Extractor {
      module: "book_extractors.common.extractors.kaira_id_extractor",
      class_name: "KairaIdExtractor"
    }
