KEYS = {
      "surname" : "surname",
      "firstnames" : "firstNames",
      "origfamily" : "originalFamily",
      "profession" : "profession",
      "imagepath": "imagePath",
      "approximatePage" : "approximatePageNumber",
      "omakotitalo" : "omakotitalo",
      "karelianlocations" : "karelianLocations",
      "karelianlocation" : "locationName",
      "returnedkarelia": "returnedToKarelia",
      "kareliancoordinate": "coordinates",
      "karelianlocationsCount": "karelianLocationCount",
      "otherlocations" : "otherLocations",
      "otherlocationsCount" : "otherLocationCount",
      "otherlocation" : "locationName",
      "othercoordinate": "coordinates",
      "manymarriages" : "maybePreviousMarriages",
      "spouseDeathYear": "deathYear",
      "childName": "name",
      "childCoordinates": "coordinates",
      "childLocationName": "location",
      "latitude": "latitude",
      "longitude": "longitude",
      "region": "region",
      "movedOut": "movedOut",
      "movedIn": "movedIn",
      "locations": "locations",

      "birthDay" :  "birthDay",
      "birthMonth" : "birthMonth",
      "birthYear" : "birthYear",
      "birthLocation" : "birthLocation",

      "address" : "address",
      "deathDay" : "deathDay",
      "deathMonth" : "deathMonth",
      "deathYear" : "deathYear",
      "kaatunut" : "fallen",
      "deathLocation" : "deathLocation",
      "talvisota" : "talvisota",
      "talvisotaregiments" : "talvisotaRegiments",
      "jatkosota" : "jatkosota",
      "jatkosotaregiments" : "jatkosotaRegiments",
      "rank": "rank",
      "kotiutusDay" : "demobilizationDay",
      "kotiutusMonth" : "demobilizationMonth",
      "kotiutusYear" : "demobilizationYear",
      "kotiutusPlace" : "demobilizationLocation",
      "medals" : "medals",
      "hobbies" : "hobbies",
      "hasSpouse" : "hasSpouse",
      "weddingYear" : "weddingYear",

      "spouse": "spouse",
      "spouseName" : "spouseName",
      "spouseProfession" : "profession",
      "spouseBirthData" : "birthData",
      "spouseDeathData" : "deathData",
      "spouseOrigFamily" : "originalFamily",
      "children" : "children",
      "gender" : "gender",
      "girlCount" : "girlCount",
      "boyCount" : "boyCount",


      "separated" : "separated",
      "miehEd" : "manPreviousMarriage",
      "nyk" : "manCurrentMarriage",
      "psoEd" : "spousePreviousMarriage",
      "wifeList" : "wives",
      "spouseCount" : "spouseCount",
      "cursorLocation" : "cursorLocation",
      "childCount" : "childCount",
      "spouseBirthLocation" : "spouseBirthLocation",
      "regiments" : "regiments"


}


